puppetlabs/puppet-strings

- README.md
- lib/puppetx/puppetlabs/strings/yard/templates/default/definedtype/html/docstring.erb
- lib/puppetx/puppetlabs/strings/yard/templates/default/definedtype/html/header.erb
- lib/puppetx/puppetlabs/strings/yard/templates/default/definedtype/html/parameter_details.erb
- lib/puppetx/puppetlabs/strings/yard/templates/default/definedtype/setup.rb
Prior to this commit, most of the HTML created for documenting
puppet code was auto-generated by YARD, meaning that it was not
always presented in a way that was consistent or easy to read. 
Now we are explicitly defining the HTML and styling that we want
to use when generating documentation for defined types and classes.
This means that we can define exactly how we want the output to look
so that is more compatible with puppet code.
I have yet to add links to any of the details around parameters because it's
not clear to me where those links should go at the moment. It should be
simple to add them though when we decide what we want them to look like.
> (PDOC-17) Add support for YARD tags in puppet code

- Gemfile
- lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_3x_function_handler.rb
- spec/unit/puppet_x/puppetlabs/strings/pops_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/puppet_3x_function_handler_spec.rb
Prior to this commit, the 3x function handler assumed that at
least two arguments (the name and one or more additional arguments)
were passed into newfunction when creating a 3x function. However
that is not actually required, the only argument needed is the name.
Update the 3x function handler so that it will not throw and exception
if only one argument is given.
> (PDOC-27) Don't require options for 3x functions

- lib/puppet_x/puppetlabs/strings/yard/core_ext/yard.rb
- lib/puppet_x/puppetlabs/strings/yard/handlers/base.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/defined_type_handler_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/host_class_handler_spec.rb
Prior to this commit, puppet namespaces would be totally mangled when
processed by YARD since YARD is looking for Ruby namespaces where the
first letter of each segment must be uppercase.
In order to fix this, patch the relevant regular expression constants
in YARD so that they will accept segments that begin with uppercase
and lowercase letters.
An upstream pull request has been accepted into YARD to add another
regex constant which is necessary to complete this patch. However until
the next version of the YARD gem is released, we must include a temporary
hack to fix the problematic method in question (as it is not yet using
the added variable). Once the new version is released, the conditional
statement in code_ext/yard.rb can be removed entirely and all we will
need to do is patch the …
> (PDOC-25) Fix mangled puppet namespaces

- Gemfile
The debugger gem does not support ruby 2.0.
The byebug gem does not support ruby < 2.0.
Conditionally specify the right gem for the right version of ruby.
> Use different debuggers for ruby 2 and 1.9

- Gemfile
- spec/unit/puppet/face_spec.rb
Prior to this commit, some of the unit tests for strings relied on
the rspec-html-matchers gem, which does not seem to get along with
rspec 3. This meant that we had to tie our tests to rspec 2 which
has become too inconvenient.
In order to remove the gem, use simple string matching instead.
Update the Gemfile so that it no longer requires the matchers and
no longer has rspec tied to 2.7.
> (maint) Remove html-matchers dependency

- lib/puppet/face/strings.rb
- lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_4x_function_handler.rb
- lib/puppet_x/puppetlabs/strings/yard/templates/default/definedtype/setup.rb
- lib/puppet_x/puppetlabs/strings/yard/templates/default/hostclass/setup.rb
- lib/puppet_x/puppetlabs/strings/yard/templates/default/puppetnamespace/setup.rb
- lib/puppet_x/puppetlabs/strings/yard/templates/default/template_helper.rb
- spec/unit/puppet/face_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/puppet_4x_function_handler_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/template_helper_spec.rb
A rude first attempt. Let's see how this goes.
For warnings we just print to stderr. Note that Yard does not print its warnings to stderr, which is a bit crude.
Note that this does not do any type checking. Presently, if I understand correctly, our handlers do not add any type information so we can't compare types with the comments.
Addresses [PDOC-37](https://tickets.puppetlabs.com/browse/PDOC-37)
> (PDOC-37) Warn when documented name does not match declared name

- lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_4x_function_handler.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/puppet_4x_function_handler_spec.rb
> Dispatch params/pdoc 37

- lib/puppet_x/puppetlabs/strings/pops/yard_statement.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/defined_type_handler_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/host_class_handler_spec.rb
The transformer comment matching regex matched all whitespace after a comment.
Lines which were effectively "blank" and just had a comment would be erased.
Markdown lists need to end with a blank line. This messed up markdown
formatting.
The culprit is the regex /^\s*#\s/ which matches all of the comment ' #\n',
however we want to leave the newline alone for markdown to parse.
We replace the regex with /^\s*#[ \t]/ which will only match tabs or spaces
after the hash and leave our beloved newline alone.
Fixes [PDOC 30 on JIRA](https://tickets.puppetlabs.com/browse/PDOC-30)
> (PDOC-30) Fix Markdown parsing lists parsing

- lib/puppet_x/puppetlabs/strings/yard/handlers/defined_type_handler.rb
- lib/puppet_x/puppetlabs/strings/yard/templates/default/html_helper.rb
Fixes issues which Shaigy found with PDOC-19:
https://tickets.puppetlabs.com/browse/PDOC-19?focusedCommentId=199417&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199417
> Forgot defined types

- lib/puppet/face/strings.rb
Suppress it by printing an empty string instead.
> (maint) Don't print extraneous "true".

- lib/puppet_x/puppetlabs/strings/yard/handlers/host_class_handler.rb
You can pass a block to the constructor of the hostclass. For some reason Yard
is yielding the block twice. Our code is not yielding the block because we only
use yield in one place which is unrelated. I don't think this is intended
behavior on yard's part, it certainly seems odd, but we can dodge the question
and not have to wait for an upstream patch by extracting the logic from the
block and running it after the object has been initialized.
> (PDOC-21) Only create HostClass parameters once

- lib/puppet_x/puppetlabs/strings/yard/templates/default/html_helper.rb
Before this commit:
packages (Array[String])- A list of packages to be installed
With this commit:
packages (Array[String]) - A list of packages to be installed
> (MAINT) Add a space between a parameter name type and its description

- lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_4x_function_handler.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/puppet_4x_function_handler_spec.rb
`lib/puppet/functions/defined.rb` has some unusual syntax:
Puppet::Functions.create_function(:'defined', ....
It runs, so apparently this is legal.
> (PDOC-45) Puppet 4x functions handle unusual names

- README.md
Add instructions on how to use the `@!puppet.provider.param` directive to
document parameters which are created via metaprogramming.
@HAIL9000 I'm going to mark this as blocked by #46
> (PDOC-35) Document documenting puppet providers

- lib/puppet_x/puppetlabs/strings/yard/templates/default/template_helper.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/host_class_handler_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/puppet_4x_function_handler_spec.rb
- spec/unit/puppet_x/puppetlabs/strings/yard/template_helper_spec.rb
1. Long warning should be broken onto multiple lines.
2. Warnings should begin with `[warn]:`
> (PDOC-49) Improve warnings

- README.md
- lib/puppet_x/puppetlabs/strings/yard/templates/default/html_helper.rb
Shaigy Nixon on Jira:
"Just a trivial thing. Looks like one line break is missing from the type's
output html between the property and the allowed values for parameter. Rest all
looks great."
https://tickets.puppetlabs.com/browse/PDOC-35?focusedCommentId=215400&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-215400
As an aside, I would really like to rewrite this method to be a real erb
template and not this nonsense.
> (PDOC-35) Format generated html properly

- metadata.json
This commit changes the metadata.json to use the
SPDX licence short identifier in the metadata.json.
SPDX is an effort from the Linux foundation to easily
parse and identify open-source licenses. Some tools
in the Puppet Ecosystem relies on those short
identifiers, like the metadata-json-lint project.
- https://spdx.org/licenses
- https://github.com/puppet-community/metadata-json-lint
> metadata.json: Use SPDX standardized short identifier for license

- .gitignore
- lib/puppet_x/puppetlabs/strings/yard/handlers/base.rb
Prior to this commit, strings would raise an error when the server
command was run against a module directory that contained the strings
module. This was due to the fact that we were trying to reference
the YARD namespace but our own namespace was being prepending to the
front, making Ruby think the two class were the same.
In order to stop this from happening, prepend a :: to the front of the
YARD version of the class to tell Ruby that we mean the YARD namespace.
> (maint) Fix ruby namespacing issue

- lib/puppet_x/puppetlabs/strings/util.rb
Without a .yardopts options array.pop is nil, and everything explodes
with an exception. Applying this patch allowed for running rake
strings:generate cleanly.
Note that this did not affect strings:serve.
> Fix issue running strings:generate without a yardopts file

- lib/puppet_x/puppetlabs/strings/yard/handlers/host_class_handler.rb
- spec/lib/strings_spec/parsing.rb
Prior to this commit, strings would fail with puppet 4.4.0 and
newer. This was because strings was making use of a method that was
marked API private and thus subject to change. The method was changed
in 4.4.0 release of puppet to take two variables, meaning that strings
much adjust how it calls the method based on the version of puppet
it's running with.
> (PDOC-75) Work with both versions of 'interpret_any'

- lib/puppet-strings/rake_tasks.rb
I'm super enthusiastic about the potential for folks to build things on
top of the JSON output, we've had several related conversations at
Config Management Camp and on puppet-dev recently. I think this is a
sane default, and calling the file strings.json seems a nice
reinforcement.
> (PDOC-70) Always generate the JSON doc when running the rake task

- README.md
- metadata.json
- puppet-strings.gemspec
Since it's been agreed that strings is better distributed as a gem, 
do the necessary updates so that we can do a final deprecated release 
of the module in conjunction with the first release of the gem. 
This will also give us a vehicle to release the last of the work @iankronquist 
did this summer and get the JSON generations into the hands of users to try
it out.
> (PDOC-74) Deprecate module in favor of gem

- .travis.yml
- Gemfile
Prior to this commit, the beaker gem and all its dependencies were
being installed just to run spec tests. Excluding beaker when running
spec tests should make things go faster because we won't have to
install so many gems.
> (maint) Don't install beaker for spec tests in travis

- README.md
Prior to this commit, the rake task section of the README did not
reflect that strings:generate rake task would also create a strings.json
file. Update the README to include this detail.
> (PDOC-70) Update rake task documentation

- lib/puppet_x/puppetlabs/strings/yard/handlers/provider_handler.rb
It will prevent providers of different types but with
the same name from merging together.
For example:
type1:ruby
type2:ruby
type3:ruby
Will be different providers instead of the one "ruby" provider.
> Add Puppet type name in front of the provider name

- Gemfile
Prior to this commit, the Gemfile did not specify an rspec version
but relied on methods that were only in rspec 3. In order to prevent
failures when running with versions older than 3, tie the specs to
3.1 or greater, which is what puppet does.
> (maint) Require rspec 3

- README.md
link to CONTRIBUTING was wrong.
example for json output has a missing yardoc option
> (doc) fix link to CONTRIBUTING / fix --emit-json option

- Rakefile
- spec/acceptance/nodesets/fedora23.yml
- spec/spec_helper_acceptance.rb
Prior to this commit, the acceptance tests were trying to install
strings as a module and failing due to the fact that strings has
transition to a gem and does not have metadata. Update the tests
so that they install strings as a gem instead.
> (maint) Update acceptance tests to use gem

- Gemfile
Prior to this commit, we were not setting a specific version of
YARD in the Gemfile. Since YARD has a lot of potential to break the
way strings works since strings relies so much on YARD internals,
we should be more deliberate about deciding to upgrade to a new
YARD version.
Once the kinks are worked out with the 0.9 release of YARD, we will
update the Gemfile again.
> (maint) Tie YARD to version 0.8.7

- lib/puppet_x/puppetlabs/strings/yard/handlers/host_class_handler.rb
This patch catches and reports on issues that have occurred during YARD
processing of the data to be processed.
The issue itself is not resolved but this does provide you with as much
documentation as can be reasonably generated for your materials without
crashing the build.
This was the result of the Baltimore Puppet Users Group Meetup of 22
June 2016.
> (PDOC-71) Workaround for spurious error failures

- spec/fixtures/unit/json/output_without_puppet_function.json
- spec/spec_helper.rb
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
- spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
The specs test functions written in the Puppet language in a few places, but
this feature is only supported in Puppet 4.1+.  This commit prevents these
specs from running if targeting older versions of Puppet.
> (PDOC-63) Fix specs for Puppet versions less than 4.1.

- README.md
- puppet-strings.gemspec
The runtime dependency on puppet presents problems when
puppet is not installed on the system as a gem, as is the
case in PE installations. Because the dependency will only be
satisfied by a gem, strings currently cannot be installed in
PE 3.8. This had to be worked around in newer PE versions with
a fake gemspec file.
Another issue is that installing strings with an older
version of puppet will force an upgrade to the newest version of
puppet via the gem.
This commit replaces the runtime dependency on puppet with a
requirement which will be present on the gem homepage on
rubygems.org. Requirements are meant to list external requirements
needed for the gem to work, which is correct for puppet as it can be
present via a different type of package.
> (PDOC-80) Remove runtime dependency on puppet

- Gemfile
Beaker 3.0 was recently released, and requires ruby > 2.0.
Since strings needs to support 1.9.3 in CI, we need to pin
beaker to < 3.0.
> (maint) Pin beaker version to < 3.0

- puppet-strings.gemspec
Strings is tested and supported for ruby 1.9.3 and above, so
the gemspec should reflect that.
> (PDOC-119) Add required ruby version to gemspec

- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
When `newfunction` is separated from the Puppet::Parser::Functions module name by a
newline, YARD ignores the namespace and uses `newfunction` as the source of the
first statement.
Prior to this commit, strings didn't recognize this case, and 3.x functions written
in this way were not parsed as functions. This commit updates the ruby function handler
to identify and properly parse 3.x functions that include a newline between the
Puppet::Parser::Function namespace and the newfunction method call.
> (PDOC-122) Properly parse `newfunction` calls with newlines

- JSON.md
- lib/puppet-strings/yard/code_objects/provider.rb
- lib/puppet-strings/yard/handlers/ruby/provider_handler.rb
- lib/puppet-strings/yard/templates/default/puppet_provider/html/collection.erb
- spec/fixtures/unit/json/output.json
- spec/fixtures/unit/json/output_without_puppet_function.json
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
Prior to this commit, strings did not properly handle providers
which had multiple related `defaultfor`s. In code, these are written
as comma-separated constraints. This commit updates strings' puppet
provider handler, as well as the template which generates HTML for
`defaultfor` statements.
Note that it was necessary to make a breaking change to the JSON
schema to accomodate multiple AND'ed defaults. Previously, provider
defaults were contained in a single key-value map. Now, they are
contained in an array of key-value maps, which allows multiple
constraints to be associated with each other.
> (PDOC-95) Properly group and display multiple provider `defaultfor`s

- lib/puppet-strings/tasks/gh_pages.rb
Previously, due to Jekyll's default rule of not allowing files beginning
with an '_' to be published, the gh_pages rake task led to broken links.
This commit adds a step to the task which adds a _config.yml file to the
`doc` directory of the gh-pages branch which explicitly allows the file
to be published.
> (PDOC-120) Update gh_pages task to allow publishing of _index.html

- lib/puppet-strings/yard/code_objects/type.rb
- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- lib/puppet-strings/yard/handlers/ruby/provider_handler.rb
- lib/puppet-strings/yard/handlers/ruby/type_handler.rb
- lib/puppet-strings/yard/util.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
- spec/unit/puppet-strings/yard/util_spec.rb
Previously, YARD would parse ruby strings which used %Q notation
and return the syntax literally. This commit adds a new Util
module with a `scrub_string` method to check for such a string
and remove the errant %Q and %q's.
> (PDOC-126) Remove `%Q` ruby quotation syntax from parsed strings

- lib/puppet-strings/tasks/gh_pages.rb
This commit updates the gh_pages task to reference the SHA
of the branch being documented in the documentation commit.
In addition, the description of each task except `update`
has been removed, as they are not useful on their own and
should be considered private. This is necessary in order
to hide the tasks from the output of `rake -T`.
> (PDOC-121) Include tag or SHA in gh_pages task commit

- README.md
Update the install instructions for the versions of Puppet Enterprise that contain Puppet 4.x
> Update README install instructions for PE

- .travis.yml
- lib/puppet-strings/yard/handlers/puppet/function_handler.rb
- lib/puppet-strings/yard/parsers/puppet/statement.rb
- spec/spec_helper.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
- spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
Previously, Strings ignored the return type in Puppet 3.x functions
that used the following syntax:
function foo() >> String {}
This commit updates the FunctionStatement class to use the return
type from such a statement if it exists.
> (PDOC-136) Detect return type syntax in Puppet Language functions

- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- spec/fixtures/unit/json/output.json
- spec/fixtures/unit/json/output_without_puppet_function.json
- spec/unit/puppet-strings/json_spec.rb
Previously, Strings ignored calls to `return_type` in Puppet 4.x API
function dispatches, preventing the return types of overloads from
being automatically determined. This commit adds a check for a node
with a `return_type` call and handles it properly.
> (PDOC-135) Detect `return_type` calls in 4.x function dispatches

- lib/puppet-strings/yard/tags/overload_tag.rb
- spec/fixtures/unit/json/output.json
- spec/fixtures/unit/json/output_without_puppet_function.json
- spec/unit/puppet-strings/json_spec.rb
Previously, overload objects were not displaying their tags when
they had no docstring text. This was due to an issue in the overload
`to_hash` method, which prevented the tags from being serialized when
the dispatch had no top-level text. This commit updates that logic
so that the tags will always be included in the hash if they exist.
> (PDOC-129) Include tags in overload objects when serialized as JSON

- README.md
Correct the examples of using a parameter type in the @param tag
so that they match how the YARD documentation suggests the tag
should be used.
http://www.rubydoc.info/gems/yard/file/docs/Tags.md#param
> (maint) Fix @param type examples in README

- Gemfile
There is currently a parsing bug in YAD 0.9.6 and above
which causes errors on certain strings with '/' characters.
We'll pin to YARD 0.9.5 until the issue is resolved on YARD's
side.
See https://github.com/lsegal/yard/issues/1054.
> (maint) Pin YARD to 0.9.5

- README.md
- lib/puppet-strings/yard/handlers/puppet/base.rb
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/class_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
Because Puppet 4 is typed, parameter type information can
be automatically determined without any explicit documentation
in @param tags. However, users may desire to do so anyway for
consistency. This commit allows @param tags to include a [type]
in Puppet 4 code. Strings will emit a warning if the documented
type does not match the actual type. In such an event, the incorrect
documented type will be ignored in favor of the real one.
> (PDOC-155) Allow type documentation in Puppet 4 code

- Rakefile
- spec/acceptance/lib/util.rb
- spec/spec_helper_acceptance.rb
* windows install requires type=aio so gem_command can find the right gem exe
* this change also allows easier command line use
* by using a sensible default for the acceptance key
* install the correct CAs in the correct places so windows can install gems
* use a gem_command abstraction to find the correct puppet gem exe
> (pdoc-144) acceptance: fix windows pre suite

- .rubocop.yml
- Gemfile
- README.md
- lib/puppet-strings/yard.rb
- lib/puppet-strings/yard/handlers/helpers.rb
- lib/puppet-strings/yard/handlers/puppet/class_handler.rb
- lib/puppet-strings/yard/handlers/puppet/defined_type_handler.rb
- lib/puppet-strings/yard/handlers/puppet/function_handler.rb
- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- lib/puppet-strings/yard/handlers/ruby/provider_handler.rb
- lib/puppet-strings/yard/handlers/ruby/type_handler.rb
- lib/puppet-strings/yard/tags.rb
- lib/puppet-strings/yard/tags/summary_tag.rb
- lib/puppet-strings/yard/templates/default/puppet_class/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_class/html/summary.erb
- lib/puppet-strings/yard/templates/default/puppet_defined_type/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_defined_type/html/summary.erb
- lib/puppet-strings/yard/templates/default/puppet_function/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_function/html/summary.erb
- lib/puppet-strings/yard/templates/default/puppet_provider/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_provider/html/summary.erb
- lib/puppet-strings/yard/templates/default/puppet_type/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_type/html/summary.erb
- spec/unit/puppet-strings/yard/handlers/puppet/class_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
This tag is primarily meant to be applied to Puppet classes,
but it is also supported by every other construct that can be
documented with strings.
> (PDOC-161) Add `summary` tag for short descriptions

- CHANGELOG.md
Github markdown needs a space after a #
> (maint) Fixing markdown formatting errors

- lib/puppet-strings/tasks/generate.rb
In the rake task strings::generate, the arguments json and yard_args
are not applied properly. The logic uses args.key?, however args is not
a Hash but a  Rake::TaskArguments (and Enumerable). There is no key?
method.
Use Rake::TaskArguments.has_key? instead.
> Fix args handling for rake strings::generate

- .travis.yml
- Gemfile
- Rakefile
This is needed in order to work with always be scheduling on CI.Next jenkins instances.
> (QENG-5344) Add beaker-abs for CI.next-i-fication

- puppet-strings.gemspec
When using puppet-strings with a module that otherwise does not specify rgen in its Gemfile, this error was observed:
```
$ bundle exec puppet strings generate ./manifests/*.pp
Error: The 'rgen' gem must be installed in order to use this face.
Error: Try 'puppet help strings generate' for usage
```
Adding rgen to the Gemfile allows puppet strings to work, so it seems like a valid runtime dependency.
> Add rgen as a runtime dependency

- lib/puppet-strings/yard/handlers/puppet/function_handler.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
This fixes the "Documented return type does not match return type" warning for Puppet functions when the types actually match.
> Fix return type matching for Puppet functions

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/defined_types.rb
- lib/puppet-strings/markdown/functions.rb
- lib/puppet-strings/markdown/puppet_classes.rb
- lib/puppet-strings/markdown/resource_types.rb
- lib/puppet-strings/markdown/table_of_contents.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/markdown/templates/table_of_contents.erb
- spec/fixtures/unit/markdown/output.md
- spec/unit/puppet-strings/markdown/base_spec.rb
- spec/unit/puppet-strings/markdown_spec.rb
If there is a class, type, or function with no information documented but is pulled in by some fluke or tag we don't support, do not give it its own section
> (maint) do not display name if there is nothing to display

- lib/puppet-strings/yard/handlers/puppet/class_handler.rb
- lib/puppet-strings/yard/handlers/puppet/defined_type_handler.rb
- lib/puppet-strings/yard/handlers/puppet/function_handler.rb
- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
There is a warning that displays when there is no text outside of tags for a given component, this text would become the 'Overview' section. The warning says: `[warn]: Missing documentation for Puppet class 'klass' at (stdin):4` The problem is that if the user has instead used the @summary tag, and is then using only tags, strings will report this warning even though there is clearly documentation. This adds a condition for the warning: If there is no text AND there are no tags, THEN output a warning saying there is no documentation.
> (maint) add condition for misleading warning

- lib/puppet-strings/yard/handlers/puppet/base.rb
- spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
Currently, if a user attempts to document the title or name params, Strings will throw a warning saying that these parameters are missing from the class/type. Of course, they aren't, they just may not be explicit. This removes the warning if the param name is 'name' or 'title'.
> (PDOC-192) remove warning for title/name

- lib/puppet-strings/yard/templates/default/layout/html/setup.rb
- lib/puppet-strings/yard/util.rb
- spec/unit/puppet-strings/yard/util_spec.rb
credit to this: https://github.com/octokit/octokit.rb/blob/0f13944e8dbb0210d1e266addd3335c6dc9fe36a/yard/default/layout/html/setup.rb#L5-L14
> (PDOC-36) hack to fix README links in generated HTML

- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
Currently, if the user is documenting a Puppet 4 type custom function and they try to use the return_type method without also including an @return tag, Strings will throw an error. This is caused by the function handler trying to add a type to a return tag on the function object that doesn't exist. To fix the problem, if you are using return_type, the handler will now add an empty return tag first if one does not exist.
> (PDOC-229) fix error with return_type and @return

- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/markdown/templates/table_of_contents.erb
- spec/fixtures/unit/markdown/output.md
- spec/fixtures/unit/markdown/output_with_plan.md
- Adds blank line padding around header elements so they will render correctly with other markdown variants
- Minor updates to make whitespace consistent
I wasn't sure how to add tests for this to prevent future updates from breaking rendering.  Someone would need to know to add blank lines around headers in the output fixtures if/when they are updated.  I thought of adding a test that would read the fixture file and check the linespace padding, but if a new fixture is added (like one was recently), someone would also need to know to add a test against the new fixture.  Testing the test fixture itself is not typical and didn't feel right.
> (PDOC-233) markdown whitespace fixes

- lib/puppet-strings/markdown/puppet_plans.rb
- lib/puppet-strings/markdown/table_of_contents.rb
- spec/fixtures/unit/markdown/output_with_plan.md
Currently, Plans are not being included in the table of contents in the
markdown output. This is because Plans were not being passed to the
table of contents renderer. This adds Plans to the renderer and updates
tests accordingly.
> (maint) display Plans in markdown table of contents

- lib/puppet-strings/yard/handlers/ruby/rsapi_handler.rb
- spec/unit/puppet-strings/yard/handlers/ruby/rsapi_handler_spec.rb
The 'features' key in the resource api expects an array of feature names. Currently, if you run strings on a resource api type that specifies features, it falls over because it doesn't know what to do with an AST node of type :array. Further, the method that throws the error is looking for an undefined variable called 'parameters'. This removes the odd conditional that calls 'parameters' and adds a method that returns an array of the array contents that may be passed to features. Features are not currently sent to the renderer, but now Strings will be able to handle any array it comes across in an rsapi type.
> (PDOC-240) add handling for :array node type in rsapi_handler

- lib/puppet-strings/yard/util.rb
- spec/unit/puppet-strings/yard/util_spec.rb
Discovered that this hack was finding broken links and then replacing all instances of the link text in the README. This led to a lot of non-links being affected. This patch works harder to match only actual links and works as far as I can tell.
> (PDOC-36) fix hack for README urls

- .travis.yml
- puppet-strings.gemspec
This is required to support some edge-case scenarios with
older puppet versions.
> (PDOC-259) relax ruby requirement to 2.1.0 from 2.1.9

- Rakefile
The (module-)`build` task from puppetlabs_spec_helper is conflicting
with the (gem-)`build` task from bundler.
> Avoid clashes with PSH's build task on release

- lib/puppet-strings.rb
- lib/puppet-strings/describe.rb
- lib/puppet-strings/yard/handlers.rb
- lib/puppet-strings/yard/handlers/ruby/base.rb
- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- lib/puppet-strings/yard/handlers/ruby/provider_handler.rb
- lib/puppet-strings/yard/handlers/ruby/type_base.rb
- lib/puppet-strings/yard/handlers/ruby/type_extras_handler.rb
- lib/puppet-strings/yard/handlers/ruby/type_handler.rb
- lib/puppet/face/strings.rb
- spec/unit/puppet-strings/describe_spec.rb
Hey @eputnam , here is that PR that I was talking about.  LMK when you have had some time to look at this, and then I would like to talk about how I can pull in the data I need to finish describe features.  Thanks!
> (PDOC-252) Add describe features to puppet-strings face

- lib/puppet-strings/markdown/base.rb
The #defaults method actually returns a Hash, not an Array.
> Correction in comments

- spec/fixtures/unit/json/output.json
- spec/fixtures/unit/json/output_with_plan.json
- spec/unit/puppet-strings/json_spec.rb
Unit tests started failing, so this change makes them pass again,
by reordering some elements in the test fixtures.
> (maint) Reorder fixtures for test failures

- lib/puppet-strings/describe.rb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/yard/code_objects/type.rb
- lib/puppet-strings/yard/handlers/ruby/type_base.rb
- spec/fixtures/unit/json/output.json
- spec/fixtures/unit/json/output_with_plan.json
- spec/fixtures/unit/json/output_without_puppet_function.json
- spec/fixtures/unit/markdown/output.md
- spec/fixtures/unit/markdown/output_with_plan.md
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
With this change, the required_features argument to newparam and newproperty is parsed.
This data is added to YARD objects and the to_hash output.  It is also added to results
for describe, json, and markdown rendering.
> (PDOC-272) Add required features attribute

- .travis.yml
This commit updates the test matix to include Puppet 6.  This commit also
removes the 2.1.9 testing on Puppet 4 as this is already performed with the
ruby 2.1.0 testing.  There is no need to test twice (162 examples in both cells)
> (maint) Add Puppet 6 to testing matrix

- .gitignore
- Gemfile
Developers may want to use additional gems during development.  This commit
updates the Gemfile to allow user and project additions to be added without the
need to checkin the Gemfile.  This is a common pattern used within Puppet.
> (maint) Allow local Gemfile overrides

- .travis.yml
- Gemfile
Currently beaker is pinned at version 2.x which causes issues on Windows with
modern Ruby.  Beaker 2.x pulls in VERY old versions of nokogiri which cannot
be compiled on Windows.  This commit updates the Beaker version pin to version
3.x as this has been out for over a year, and will allow developers on Windows
to at least do a bundle install.  Later commits may update this to the latest
beaker version (4.x)
> (maint) Update very old Beaker version in Gemfile

- lib/puppet-strings/yard/handlers/ruby/base.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
Previously in Yard 0.9.19 dyna_symbols (symbols represented as strings e.g.
:'something') were converted to their unqualified symbol name e.g. :something.
However YARD treated this as a bug and in Yard 0.19.20 dynasymbols are now their
original source.  This commit modifies the base ruby handler to always convert
dyna_symbols to their plain name, as Puppet uses this for actual documentation
and Puppet Code.  For example the fully qualified function 'foo::bar' will
appear in the ruby function definition as `.. :'foo::bar'` however in the Puppet
documentation the name should appears as `foo::bar`.
This commit also adds tests for this scenario as there were no existing tests
for this.
> (PDOC-283) Fix namespaced symbols

- lib/puppet-strings/yard/handlers/ruby/base.rb
Previously the base handler used a naive method to determine the name of a
dyna_symbol.  This commit updates the handler to instead use the actual ruby
AST to determine the string content.  This was tested on ruby 0.9.20 and
0.9.19.  No tests were changed as there is no change in behaviour.
> (PDOC-283) Use AST to determine dyna_symbols

- lib/puppet-strings/yard/handlers/ruby/base.rb
Now that ruby AST is used to determine the string content for function names we no longer need to detect yard version.
> (maint) Remove unused yard_version method

- lib/puppet-strings/yard/handlers/ruby/data_type_handler.rb
- spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb
Previously the data_type_handler would throw errors if the ruby datatype had
errors in the puppet interface definition.  This commit traps the Puppet Syntax
Errors and throws a useful warning explaining where the error occured and allows
yard to continue parsing.
Previously numeric default values were not being detected correctly.  This
commit updates the Literal Evaluator to understand negative values and also adds
tests for the different kinds of Puppet Literal Numbers.
> (PDOC-285) Fix data_type_handler for errors and numbers

- lib/puppet-strings/yard/code_objects/task.rb
- spec/spec_helper_acceptance.rb
When a task doesn't have parameters and a user generates markdown for
the task, this line would error because it can't iterate on `nil`. This
modifies it to use the `TaskStatement` method `parameters` which sets a
default empty hash when a task doesn't have parameters.
> (maint) Use parameters method instead of json['parameters']

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/yard.rb
- lib/puppet-strings/yard/code_objects/function.rb
- lib/puppet-strings/yard/tags.rb
- lib/puppet-strings/yard/tags/enum_tag.rb
- lib/puppet-strings/yard/tags/factory.rb
- lib/puppet-strings/yard/util.rb
- spec/fixtures/unit/markdown/output.md
- spec/fixtures/unit/markdown/output_with_data_types.md
- spec/fixtures/unit/markdown/output_with_plan.md
- spec/unit/puppet-strings/markdown_spec.rb
`Enum` data types would benefit from the ability to add extended
documentation on each option similarly to the `@option` tag
for hashes. The `@option` type is not a good fit for `Enum` data
type parameters as it requires data types to be specified,
which doesn't make sense in the context of an `Enum` type.
This patch adds a new `@enum` tag which behaves like @option,
but does not accept the data type parameter that `@option` does.
> (PDOC-295) Add @enum tag support for Enum data types

- lib/puppet-strings/yard/tags/enum_tag.rb
- lib/puppet-strings/yard/templates/default/tags/html/enum.erb
- lib/puppet-strings/yard/templates/default/tags/setup.rb
- spec/acceptance/running_strings_generate_spec.rb
- spec/fixtures/acceptance/modules/test/manifests/init.pp
In #215 support for the new `enum` tag was added. Unfortunately, all of the testing was with markdown generation and it escaped me that HTML output was not automatically included. This patch adds the HTML output generation for the `enum` tag which should have been included in #215
> Add missing HTML output support for enum tag

- .travis.yml
- Gemfile
- Rakefile
Currently the litmus based testing is broken due to bugs in both Litmus and
Bolt.  This commit modifies the acceptance testing to:
* Use a fixed fork of Litmus to enable the instal_modules_from_directory rake
task
* Monkey patches Bolt to be able to used due to Bolt Issue 1614
These parts can be reverted once their related PRs are merged and released.
> (MAINT) Fix litmus testing

- Gemfile
- spec/spec_helper.rb
- spec/unit/puppet-strings/markdown_spec.rb
Previously the markdown generated by Puppet-Strings may contain errors which
markdown lint programs would flag.  This commit adds the ability to run markdown
lint on a per test basis and adds pending tests to show that the markdown output
does indeed need some work.
Note that this commit does not fix the errors.  That will come in later commits.
> (maint) Add markdown lint checking to markdown tests

- lib/puppet-strings/markdown/resource_type.rb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/yard/code_objects/type.rb
- lib/puppet-strings/yard/handlers/ruby/type_base.rb
- lib/puppet-strings/yard/handlers/ruby/type_handler.rb
- lib/puppet-strings/yard/templates/default/puppet_type/html/setup.rb
- spec/fixtures/ruby/resource_type.rb
- spec/unit/puppet-strings/markdown_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
> Add checks to resource_type handler and code objects

- Gemfile
Previously the litmus gem was pinned to a version in Michael Lombardi's fork.
This commit removes the pin as the PR mentioned was merged into Litmus 0.16.0
Ref - https://github.com/puppetlabs/puppet_litmus/commit/f09c9db745e2fdded9ebc75dec1705e39722acdb
> (maint) Remove pin to custom version of Litmus

- puppet-strings.gemspec
Previously the gemspec was using 'git ls-file' to retrieve the file list for
the gem, however this is problematic during development as untracked files are
not added, which can then cause an incomplete gem tarball to used during the
acceptance tests, which cause false negative test results.
This commit updates the Gemspec to use the more common Dir[..] method as used in
the PDK.
> (maint) Do not use git for Gemspec files

- lib/puppet-strings/markdown/base.rb
b5da040babf4bdbbcfd9bfabdb210041ccfa8ce3 introduced word_wrap which assumes text is a string. However, this is not true and not every resource type has a description.
> Handle a missing description gracefully

- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/data_type_function.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/puppet_task.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- spec/markdownlint_style.rb
- Added parameter list for classes, defines, data types and resource types with links to detailed parameter description. Useful for classes that have lots of parameters
- Fixed anchor links in markdown templates — original ones didn't work at Bitbucket
> Improved markdown templates

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/templates/resource_type.erb
* The resource_type ERB file would fail on parameters without
descriptions. These are a warning but should not cause a hard failure
* Added a log message to help isolate the file where issues are
occurring
> Fix ERB failure - parameters without descriptions

- lib/puppet-strings/yard/handlers/puppet/function_handler.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
Currently puppet-strings fails if function documentation tag `return` has no type specified with "NoMethodError: undefined method `first' for nil:NilClass", so you either have no return tag or have to duplicate function return type in return tag.
This PR allows you to omit specifying return type.
> Do not fail in case return tag has no type specified

- lib/puppet-strings/yard/handlers/ruby/type_extras_handler.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_extras_handler_spec.rb
Puppet's `file` type uses the `ensurable` method in an extra file, so add
support for that.
> Add support for ensurable in types_extras_handler

- lib/puppet-strings/yard/code_objects/type.rb
cc @nkanderson 
See https://forge.puppet.com/modules/enterprisemodules/ora_install/5.12.3 for an example of a module that would trigger an error before.
Error triggered was:
```
$ bx puppet strings generate --format json /Users/jesse/tmp/enterprisemodules-ora_install-5.12.3/ --trace
Error: undefined method `any?' for nil:NilClass
/Users/jesse/src/puppet-strings/lib/puppet-strings/yard/code_objects/type.rb:155:in `parameters'
/Users/jesse/src/puppet-strings/lib/puppet-strings/yard/code_objects/type.rb:187:in `to_hash'
/Users/jesse/src/puppet-strings/lib/puppet-strings/json.rb:16:in `map!'
/Users/jesse/src/puppet-strings/lib/puppet-strings/json.rb:16:in `render'
/Users/jesse/src/puppet-strings/lib/puppet-strings.rb:78:in `render_json' …
```
> (FIXUP) Check for nil before injecting provider param into Types

- lib/puppet-strings/yard/code_objects/type.rb
Original PR: #288
Fixed up a typo in the comment
-----------------
In some rare cases where no parameter is (yet) defined in the type, an error is thrown
```
Error: undefined method `any?' for nil:NilClass
```
Closes: #287
> Fix rare undefined method `any?' for nil:NilClass error

- .fixtures.yml
- .gitignore
Previously, acceptance tests were failing during the initial installation of fixtures:
> Cloning into 'spec/fixtures/modules/puppet_agent'...
> fatal: unable to connect to github.com:
> github.com\[0: 140.82.113.4]: errno=Connection timed out
This switches to using `https` URLs for the fixtures, which allows acceptance tests to proceed beyond that point.
---
I don’t normally use Docker, so it’s hard for me to tell what’s problem on my machine and what’s a problem with the acceptance testing setup. I’m getting errors while spinning up the CentOS container:
> Failure connecting to localhost:52595:
> {"target"=>"localhost:52595", "action"=>"command", "object"=>nil, "status"=>"failure", "value"=>{"_error"=>{"details"=>{}, "kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Failed to connect to …
> Fix acceptance tests

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/resource_type.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- spec/unit/puppet-strings/markdown/base_spec.rb
Previously, anchors in generated Markdown were not unique. There were two problems:
1. Each parameter in a class, type, function, etc. had its own anchor, but the `name` of the anchor was just the normalized name of the parameter. This meant that all parameters with the same name would have the same anchor.
2. Classes, types, etc. had their `::`s removed, whiched opened the (rare) possibility of having non-unique anchor names for unique type names.
This fixes those problems by:
1. Using the full name of the parameter, e.g.  `$my::class::param`, to generate an anchor name.
2. Using a better anchor normalization routine. Each invalid character, i.e. not `[a-zA-Z0-9_-]`, is converted to `-`. This should always result in unique anchor names for standard Puppet identifiers, since the only …
> (#300) Fix anchor links in Markdown docs

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
Previously, some values in generated Markdown were wrapped in double backticks instead of single backticks. This removes the code that added the extra backticks.
See #304.
> (#304) Fix double backticks in Markdown

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/table_of_contents.rb
This has to special case Ruby <2.6.0 since those versions will interpret the keyword argument as a hash passed as the second argument.
Without this change running this code in Ruby 2.6+ will generate warnings about the parameters passed to `ERB.new`.
---
I’ve run the tests under Ruby 2.3.0 (with some dificulty; see #301) and this appears to work. At the very least it clears up all the warnings.
> (#302) Fix warnings generated by ERB.new

- CODEOWNERS
Prior to this commit the CODEOWNERS file for this repository referenced the devx team.
Since the efforts of this team have been merged in to CaT (modules) this commit changes the associated group to @puppetlabs/modules.
> (MAINT) Update CODEOWNERS

- .rubocop.yml
- Gemfile
- puppet-strings.gemspec
- spec/spec_helper.rb
- spec/unit/puppet-strings/markdown_spec.rb
Previously, the minimum Ruby version was 2.3.0, but it was dificult to get it working and some of the code had been updated to use features as new as 2.4.6.
This clears out code that checked for old Ruby versions, and removes some version constraints in Gemfile that were needed to work with Ruby 2.3.0.
> (#301) Update minimum Ruby version to 2.5.0

- lib/puppet-strings/yard/parsers/puppet/parser.rb
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
This is an alternate to #311, which fixes this same problem in a different way. I like this solution better.
Previously, the tests for `PuppetStrings::Json` (in json_spec.rb) parsed a variety of code samples and then queried YARD to test the results. Ifa sample failed to parse, an error might be outputted (see [issue #307][#307]), but no failure was registered by the testing harness.
This adds simple checks to verify that the parses actually succeed.
Unfortunately, one of the samples currently fails to parse, so this commit introduces a testing error. The subbsequent commit will fix it.
[#307]: https://github.com/puppetlabs/puppet-strings/issues/307
Previously, the parsing code activated task support in Puppet when it detected that it was parsing a file in a plans/ directory. This casued …
> (#307) Always enable plan parsing

- lib/puppet-strings/yard/handlers/ruby/data_type_handler.rb
- lib/puppet-strings/yard/parsers/puppet/statement.rb
- lib/puppet-strings/yard/util.rb
- spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
- spec/unit/puppet-strings/yard/util_spec.rb
Previously, parameters with a default value that was an expression were not outputted into the documentation correctly. For example,
Integer $param = 1 + 1,
Would be shown in the documentation to have a default value of “+”.
This switches to using `extract_tree_text` instead of `extract_text` to get the text representation of the parsed Puppet code.
This also gets rid of the dependency on `Puppet::Pops::Adapters::SourcePosAdapter`, which was [deprecated in 2017](https://github.com/puppetlabs/puppet/commit/68498adfa2560c9cbf28d7a46ebc1aef14c69992).
Unfortunately, it appears that there is a bug in Puppet ([PUP-11632][]) that sometimes returns the incorrect default value. This adds two skipped tests that demonstrate the issue.
[PUP-11632]: https://tickets.puppetlabs.com/browse/PUP-11632
> (#240) Fix output of default values that are expressions

- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/helpers.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/data_type_function.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/puppet_task.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- spec/unit/puppet-strings/markdown_spec.rb
Sometimes data types, default values, and other code outputted in Markdown documentation is multiline. When that’s the case, it’s cleaner to use a code block (below) rather and inline code (`code`).
```
example code block
with two lines
```
This updates the Markdown template code to use code blocks in many places if the code in question contains a newline.
Thanks to @crazymind1337 for the example of a multiline type alias!
> (#223) Use code blocks as appropriate in Markdown

- .github/workflows/release.yml
- .github/workflows/release_prep.yml
- .gitignore
Prior to this PR releasing `puppet-strings` was a manual effort.
This PR adds two new workflows:
This workflow will update the changelog based on the version specified in the current gemspec.
It does not automatically generate the next version number. This will need to be done in a commit before this workflow is executed.
This workflow will build a new gem, create a GitHub release (and tag), upload the gem as a release asset and finally push the gem to rubygems.org.
> (MAINT) Add release workflows

- .github/workflows/snyk.yml
Prior to this commit an incorrectly configured twingate step was causing the workflow to fail.
We don't actually need twingate so this commit removes the step and hopefully allows it to continue scanning.
> (MAINT) Fix snyk workflow

- .github/workflows/labeller.yml
This PR introduces the community labeller action. It's purpose is to appropriately label community issues and PRs.
> (MAINT) Add community labeller

- .rubocop.yml
- spec/acceptance/generate_markdown_spec.rb
- spec/fixtures/acceptance/modules/test/lib/puppet/datatypes/acceptancedatatype.rb
- spec/fixtures/ruby/data_type.rb
- spec/fixtures/ruby/func3x.rb
- spec/fixtures/ruby/resource_api.rb
- spec/fixtures/ruby/resource_type.rb
- spec/unit/puppet-strings/describe_spec.rb
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/markdown/base_spec.rb
- spec/unit/puppet-strings/yard/code_objects/task_spec.rb
- spec/unit/puppet-strings/yard/handlers/json/task_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/class_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/data_type_alias_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/rsapi_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_extras_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
- spec/unit/puppet-strings/yard/parsers/json/parser_spec.rb
- spec/unit/puppet-strings/yard/parsers/json/task_statement_spec.rb
- spec/unit/puppet-strings/yard/parsers/puppet/parser_spec.rb
- spec/unit/puppet-strings/yard/util_spec.rb
This changes most heredocs to use the tilde syntax with variable interpolation off. It indents the contents of the heredoc along with the final symbol.
To maintain these changes, it enables `Layout/HeredocIndentation` and `Layout/ClosingHeredocIndentation` in Rubocop.
The tilde syntax smartly strips the indentation, and allows for different indention of the closing identifier:
```ruby
"test\n" == <<~'END'
test
END
```
This syntax was introduced in Ruby 2.3.0, so this will not pose compatibility problems.
> Use tilde heredocs for readability

- .github/workflows/ci.yml
- Gemfile
- Rakefile
- puppet-strings.gemspec
This PR preps puppet-strings to use the new reusable GitHub actions. We've surface the matrix in calling workflows now and also changed the way the acceptance tests work. When calling the reusable acceptance workflow, it expects that the caller implements a rake task called acceptance with the required steps inside.
> (MAINT) Add matrix for acceptance tests

- Gemfile
Prior to this PR the version of rake installed with this project was vulnerable to an OS command injection attach.
The CVE ID for this is: CVE-2020-8130
This PR fixes the above by removing the version constraint and ensuring that the latest version of rake is always pulled.
> (MAINT) Remove version constraint for rake

- .rubocop.yml
- puppet-strings.gemspec
This PR bumps the minimum required ruby version to 2.7.
> (MAINT) Bump ruby version

- Gemfile
It looks like there was a version bump of mdl this week which introduced some markdown violations.
This commit pins mdl to 0.11.0 to give us time to investigate the changes and keep ci working.
> (MAINT) Pin MDL to 0.11.0

- lib/puppet/face/strings.rb
- spec/acceptance/generate_json_spec.rb
Given that we are working towards a 3.0.0 release, this commit removes the two deprecated `emit_*` flags in favour of
`--format` and `--out`.
> (CONT-228) Remove deprecated emit flags

- lib/puppet-strings/version.rb
This commit bumps the puppet-string gem version to v3.0.0.
> (MAINT) Bump gem version

- lib/puppet-strings/tasks.rb
Prior to this PR users would receive an Undefined Constant error when attempting to generate a reference file via the provided Rake tasks.
This was caused by the compact testing style for modules added in v3.0.
In this case the parent, PuppetStrings is not properly loaded before Tasks. As a result the error above is caused.
This PR adds a new module declaration to tasks.rb that will ensure that the PuppetStrings is properly loaded.
> (GH-332) Ensure PuppetStrings is loaded for tasks

- README.md
Prior to this pr, the minimum puppet version requirement in the README was set to 6.
Given that the latest strings support is pinned to ruby 2.7, it is no longer compatible with puppet 6.
Therefore, this pr updates the minimum puppet version to 7.
> (MAINT) Update required version info

- Gemfile
- lib/puppet-strings/markdown/base.rb
- lib/puppet-strings/markdown/templates/classes_and_defines.erb
- lib/puppet-strings/markdown/templates/data_type.erb
- lib/puppet-strings/markdown/templates/function.erb
- lib/puppet-strings/markdown/templates/resource_type.erb
- lib/puppet-strings/yard/templates/default/puppet_class/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_class/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_data_type/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_data_type/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_data_type_alias/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_data_type_alias/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_defined_type/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_defined_type/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_function/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_function/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_plan/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_plan/html/setup.rb
- lib/puppet-strings/yard/templates/default/puppet_type/html/deprecated.erb
- lib/puppet-strings/yard/templates/default/puppet_type/html/setup.rb
- spec/fixtures/puppet/class.pp
- spec/unit/puppet-strings/json_spec.rb
- spec/unit/puppet-strings/markdown/base_spec.rb
- spec/unit/puppet-strings/markdown_spec.rb
I had a stab at adding the deprecated flag
Fixes #339
> Add deprecated tag

- README.md
Prior to this commit the README referenced puppet6 which is no longer supported.
This commit updates an example usage of litmus to install a newer version of puppet.
> Remove puppet6 reference in README.md

- lib/puppet-strings.rb
- lib/puppet-strings/describe.rb
- lib/puppet-strings/yard/handlers/ruby/function_handler.rb
- lib/puppet/face/strings.rb
This PR finishes the implementation of the `providers` flag as this was never completed.
It also adds a new flag that can be used to list all available providers and their respective types within the module.
adding `--providers` to a describe command i.e. `describe firewall --providers`, returns the providers for the firewall type.
running `--list-providers` lists all providers in the module.
> (CONT-1193) - Add `--providers` and `--list-providers` flags

- lib/puppet-strings/yard/tags/overload_tag.rb
https://msp-greg.github.io/rubocop/RuboCop/Cop/Style/ArgumentsForwarding.html
> (maint) - fix rubocop

- lib/puppet-strings/markdown/templates/classes_and_defines.erb
Do not error if no data types are provided to the option tag. Instead, generate a suitable line excluding the data type.
When using the `@option` tag if a data type is not specified then rendering to Markdown will result in an exception being raised.  This fixes that so an appropriate documentation line is emitted instead.
> Fix option tag handling with no data types

- lib/puppet-strings/describe.rb
- lib/puppet-strings/yard/code_objects/function.rb
- lib/puppet-strings/yard/code_objects/provider.rb
- lib/puppet-strings/yard/code_objects/type.rb
- lib/puppet-strings/yard/util.rb
Fix [failing nightly CI rubocop warnings](https://github.com/puppetlabs/puppet-strings/actions/runs/7080261619/job/19267899940):
```bash
➜  puppet-strings git:(maint_fix_rubocop_warnings) bundle exec rubocop --format github
::error file=lib/puppet-strings/describe.rb,line=69,col=44::Layout/ExtraSpacing: Unnecessary spacing detected.
::error file=lib/puppet-strings/yard/code_objects/function.rb,line=11,col=11::Lint/SymbolConversion: Unnecessary symbol conversion; use `:"puppet_functions_#{type}"` instead.
::error file=lib/puppet-strings/yard/code_objects/provider.rb,line=11,col=11::Lint/SymbolConversion: Unnecessary symbol conversion; use `:"puppet_providers_#{type}"` instead.
::error file=lib/puppet-strings/yard/code_objects/type.rb,line=172,col=36::Lint/SymbolConversion: Unnecessary …
```
> (maint) Fix rubocop lint warnings

- lib/puppet-strings/yard/tags/overload_tag.rb
This reverts commit e6b70be9e7a4eaaf50d7eaf8d8172649b6350dcb.
Fixes https://github.com/puppetlabs/puppet-strings/issues/375
> Revert "(maint) - fix rubocop" Leading argument with delegation syntax not supported with ruby 2.7.0

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- Gemfile
- Rakefile
- spec/spec_helper.rb
"(CAT-1618) - Add code coverage to ci"
pdk version: `3.0.0`
> pdksync - "(CAT-1618) - Add code coverage to ci"

- lib/puppet-strings/markdown.rb
- lib/puppet/face/strings.rb
See individual commits for details, but they both come down to checking `RUBY_VERSION` for some old version while the gemspec declares 2.7 as the lower bound.
> Drop outdate Ruby version checks

- lib/puppet-strings/tasks/validate.rb
This is the command we use with @voxpupuli modules ([ref](https://voxpupuli.org/docs/how_to_run_tests/#referencemd-update)), not sure what the correct way is for PDK modules.
> validate: give hint on how to regenerate outdated REFERENCE.md

- spec/unit/puppet-strings/yard/handlers/puppet/class_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/data_type_alias_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/defined_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/puppet/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/function_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/provider_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/rsapi_handler_spec.rb
- spec/unit/puppet-strings/yard/handlers/ruby/type_handler_spec.rb
Prior to this commit, the nightlies were failing due to a change in Rubocop. This PR addresses the failures.
Provide a detailed description of all the changes present in this pull request.
> (maint) Address rubocop failures in unit tests

- .rubocop.yml
- Gemfile
- lib/puppet-strings/yard/code_objects/task.rb
- lib/puppet-strings/yard/handlers/ruby/provider_handler.rb
- lib/puppet-strings/yard/parsers/puppet/statement.rb
- lib/puppet-strings/yard/tags/overload_tag.rb
Reverts puppetlabs/puppet-strings#393
> Revert "(maint) Exclude breaking rubocop versions"

- puppet-strings.gemspec
Yard 0.9.37 was released, which broke our pipeline and also broke some module CI.
This commit adds a temporary pin to the gem to < 0.9.37, until we can resolve these issues.
> (bug) - Pin yard to < 0.9.37

- puppet-strings.gemspec
- spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb
Monkey patching libraries is a bad idea.  Latest version of yard changed
some internal details, which broke CI.
A workaround was proposed in #401 but the root cause was not addressed.
In this commit, we replace the private `io` object with an instance of a
class that provide the expected `IO#write` method instead of `nil` which
does not provide this interface in CI, so that the issue is not raised
anymore.
> Fix CI with latest yard

- lib/puppet/face/strings.rb
This is part of the OpenVox rebranding. This summary string is part of
the `puppet --help` output.
Provide a detailed description of all the changes present in this pull request.
> clarifies the puppet-strings usage

- puppet-strings.gemspec
puppe is a runtime dependency:
```
$ git grep "require 'puppet/"
lib/puppet-strings/yard/parsers/puppet/parser.rb:require 'puppet/pops'
lib/puppet-strings/yard/parsers/puppet/statement.rb:require 'puppet/pops'
lib/puppet-strings/yard/util.rb:require 'puppet/util'
lib/puppet/application/strings.rb:require 'puppet/application/face_base'
lib/puppet/face/strings.rb:require 'puppet/face'
lib/puppet/feature/rgen.rb:require 'puppet/util/feature'
lib/puppet/feature/yard.rb:require 'puppet/util/feature'
spec/spec_helper.rb:require 'puppet/version'
```
Provide a detailed description of all the changes present in this pull request.
> List puppet as runtime dependency

- .rubocop.yml
- lib/puppet-strings/tasks/gh_pages.rb
Without this commit, you cannot inform the rake task to push gh-pages to accept a different commit message. This is necessary in environment where commit messages have to be in specific formats.
None of the system calls were checking the exit status of their respective commands. Not stopping on error means that the rake take can fail and you and your pipelines would not know.
> Rake task allows for a different commit message

- README.md
README updated. The URL for the community Slack has been updated to correctly point to https://puppetcommunity.slack.com/ instead of https://slack.puppet.com
> (doc) Fixing link to Community Slack
