.travis.yml

Enable docker containers for travis so it will run faster.

(maint) Enable docker containers for travis

---

metadata.json

Otherwise there are issues installing/removing/upgrading

Make the metadata match what's generated by the PMT

---

lib/puppet_x/puppetlabs/strings/yard/code_objects/defined_type_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/host_class_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/puppet_namespace_object.rb
lib/puppet_x/puppetlabs/strings/yard/handlers/host_class_handler.rb
lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_4x_function_handler.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/hostclass/setup.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/puppetnamespace/setup.rb
lib/puppet_x/puppetlabs/strings/yard/templates/default/template_helper.rb
spec/unit/puppet_x/puppetlabs/strings/yard/puppet_4x_function_handler_spec.rb
spec/unit/puppet_x/puppetlabs/strings/yard/template_helper_spec.rb

Type checking/pdoc 21

---

lib/puppet_x/puppetlabs/strings/yard/handlers/host_class_handler.rb

Addresses @hlindberg's comment after PR #35 was closed.

(maint) Remove unused code path

---

README.md

Also includes a variety of other README updates and modernizations.

(PDOC-33) Inform reader how to install yard gem

---

lib/puppet_x/puppetlabs/strings/yard/templates/default/definedtype/setup.rb

@HAIL9000 Shaigy pointed this out to me.

(PDOC-21) Check mismatched types in defined types

---

lib/puppet_x/puppetlabs/strings/yard/templates/default/hostclass/setup.rb
spec/lib/strings_spec/module_helper.rb
spec/unit/puppet/face_spec.rb
spec/unit/puppet_x/puppetlabs/strings/yard/examples/test/manifests/init.pp
spec/unit/puppet_x/puppetlabs/strings/yard/host_class_handler_spec.rb

@HAIL9000 could you test this really well please? Also includes a fair bit of refactoring which needed to happen.

(PDOC-21) Duplicate warnings

---

Gemfile
README.md
lib/puppet-strings/rake_tasks.rb
lib/puppet/face/strings.rb
lib/puppet_x/puppetlabs/strings/util.rb
puppet-strings.gemspec

This is a reimplementation of #34 so as to be more maintainable :)

(PDOC-28) Make puppet strings available as a gem

---

README.md
json_dom.md
lib/puppet/face/strings.rb
lib/puppet_x/puppetlabs/strings.rb
lib/puppet_x/puppetlabs/strings/util.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/defined_type_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/host_class_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/method_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/provider_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/puppet_namespace_object.rb
lib/puppet_x/puppetlabs/strings/yard/code_objects/type_object.rb
lib/puppet_x/puppetlabs/strings/yard/handlers/puppet_3x_function_handler.rb
lib/puppet_x/puppetlabs/strings/yard/handlers/type_handler.rb
lib/puppet_x/puppetlabs/strings/yard/json_registry_store.rb
lib/puppet_x/puppetlabs/strings/yard/monkey_patches.rb
spec/unit/puppet_x/puppetlabs/strings/yard/type_handler_spec.rb

Addresses [PDOC-23](https://tickets.puppetlabs.com/browse/PDOC-23).
Nick had some ideas about its current form and this will need to be extended once #46 is merged. I'm putting it up here anticipating our meeting Tuesday the 8th.

(PDOC-23) Emit json

---

README.md

Update the README so that it is accurate

(maint) Make some small updates to the README

---

README.md

Some minor fixes to the README that need correction following the recent
refactoring commit.

(maint) Minor fixes to README.

---

spec/acceptance/emit_json_options.rb
spec/acceptance/lib/util.rb
spec/acceptance/running_strings_generate.rb
spec/spec_helper_acceptance.rb

These commits also add an acceptance helper module and add it to the LOAD_PATH.

(PDOC-106) Add acceptance tests for --emit-json options

---

README.md

@whopper , here's my revision on the Strings README!

(PDOC-133) revise+edit strings readme

---

README.md

The readme says we support all YARD tags. Turns out, we don't!

(PDOC-196) Correcting misinformation about supported YARD tags

---

README.md

Spelling README.md

---

lib/puppet-strings/tasks/generate.rb

This makes it easy to generate just a reference

(maint) Implement a strings:generate:reference task

---

README.md

(MAINT) Update install instructions for puppet-agent versus gem install

---

lib/puppet-strings.rb

Expanded default search glob for plans, so that they are found in subfolders of the plans folder as well. Bolt is already able to load plans from subfolders.

Expanded default search glob for plans.

---

lib/puppet-strings/markdown/templates/table_of_contents.erb

Eliminate trailing spaces w/o descriptions

---

lib/puppet-strings/yard/templates/default/puppet_function/html/setup.rb

Move start of nesting to 'note' in setup.rb, otherwise nesting is not affected by yield in overview.

puppet_function template: fix tags, source

---

CHANGELOG.md
lib/puppet-strings/version.rb

This also contains some old commits from `master` so that we can finally delete the old branch.

Release prep for 2.6.0

---

.rubocop_todo.yml
CHANGELOG.md
COMMITTERS.md
CONTRIBUTING.md
HISTORY.md
README.md
Rakefile
misc/ANNOUNCEMENT_TEMPLATE.md
spec/unit/puppet-strings/yard/handlers/ruby/data_type_handler_spec.rb

Removal of any inappropriate or offensive terminology from the code base.

(IAC-1459) - Removal of Inappropriate Terminology

---

README.md

README.md: update link to docs

---

.travis.yml

removal of unsupported puppet / ruby combinations
addition of puppet 7

(maint) Update travis matrix 

---

.travis.yml
Rakefile

Added puppet7 acceptance tests
Added support for gem native extensions in acceptance tests
Fixed reporting of errors from the rake tasks

(maint) Improve acceptance tests

---

lib/puppet-strings/tasks.rb
lib/puppet-strings/tasks/validate.rb

This task can validate whether REFERENCE.md is still in sync.

Implement a strings:validate:reference task

---

README.md

This PR includes a few updates to the readme.
* Included a CI badge and removed existing travis badge
* Cleaned up based on markdown lint suggestion
* Use in line linking where applicable
* Remove links table given that it is now available elsewhere
* Update version requirements

(MAINT) Refresh readme

---

.github/workflows/ci.yml

This PR updates the existing ci workflow so that it consumes the gem_ci reusable workflow.

(MAINT) Update CI workflow

---

CONTRIBUTING.md

Removing an old link that no longer works.

(maint) Update CONTRIBUTING.md

---

.github/workflows/jekyll-gh-pages.yml

Provide a detailed description of all the changes present in this pull request.

Fix workflow name
